version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: course_enrollment_db
    environment:
      POSTGRES_USER: vrunda
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: course_enrollment
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/procedures.sql:/docker-entrypoint-initdb.d/02-procedures.sql
      - ./db/views.sql:/docker-entrypoint-initdb.d/03-views.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/04-seed.sql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: course_enrollment_backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=vrunda
      - DB_HOST=db
      - DB_NAME=course_enrollment
      - DB_PASSWORD=password123
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
